### ISSUE TITLE
Question: will lambda association be lost when editing distribution settings.

### ISSUE THREAD

**Issue by shineli1984** [silvermine/serverless-plugin-cloudfront-lambda-edge#10]
Hi.

I just want to double check if the cloudfront distribution resource is edited in `serverless.yml`, does this plugin do the following:
1. update the resource **without** the `Lambda Function Associations`
2. waiting for distribution to be deployed
3. update `Lambda FunctionAssociations` on same distribution with the new version of lambda.

If so, is there a way to make sure the editing of distribution resource in the in step 1 above does not override the previous associations?

**Comment by prabinv** [comment]
@shineli1984 Just tried updating the Cloudfront distribution settings on a serverless project which uses the Lambda Edge CloudFront plugin, and can confirm that it did drop the Lambda associations.

**Comment by jthomerson** [comment]
@shineli1984 as described in the [README](https://github.com/silvermine/serverless-plugin-cloudfront-lambda-edge/blob/279b8014b981bfafac18b73e579cca992bc78287/README.md) and a bit more in #1 and #7, this plugin was manually adding the Lambda function associations as an update to the CloudFront distribution *after* the distribution was deployed by CloudFormation. This was *before* CloudFormation added support for `LambdaFunctionAssociations`.

We are currently working on v2.0 of the plugin (as described in #1 and #7), which will merely update the CloudFormation stack that is generated by Serverless. Thus, the plugin would no longer overwrite any other function associations you managed to define in your serverless.yml file.

Keep your eyes open for v2.0 in the next week or so.
