### ISSUE TITLE
Error: Stack "{stack}" did not have an output with name "{name}LambdaFunctionQualifiedArn"

### ISSUE THREAD

**Issue by aquaticpond** [silvermine/serverless-plugin-cloudfront-lambda-edge#11]
Plugin is looking for something from lambda in Outputs but no corresponding thing exists in outputs? I cant tell if this is a serverless bug or a plugin bug.

**Comment by aquaticpond** [comment]
So after some digging I've discovered:

1) The function in this package: index.js:274 _getFunctionsToAssociate requires the lambda ARN with version number. I'm not sure how I'm supposed to provide this, there is no Serverless documentation for appending lambda ARN with version number to the `Resources: Outputs: ...` directive. Right now I literally have my ARN:version_number hard coded in your package code which is the only way I can seem to get it to almost work.

2) Lambda@edge requires function versioning. I can't find any Serverless documentation for automating this process either. Obviously I can version and deploy the function by clicking through the AWS interface, but I really want this all to happen automagically.

**Comment by jthomerson** [comment]
@aquaticpond in a previous response that it looks like you have since deleted, you said:

> So after some digging I've discovered:
>
> 1. The function in this package: index.js:274 _getFunctionsToAssociate requires the lambda ARN with version number. I'm not sure how I'm supposed to provide this, there is no Serverless documentation for appending lambda ARN with version number to the Resources: Outputs: ... directive. Right now I literally have my ARN:version_number hard coded in your package code which is the only way I can seem to get it to almost work.
>
> 2. Lambda@edge requires function versioning. I can't find any Serverless documentation for automating this process either. Obviously I can version and deploy the function by clicking through the AWS interface, but I really want this all to happen automagically.

Have you followed the instructions on the project's README? It gives a complete working example. If you try that and are still unable to get it working, please provide a complete `serverless.yml` file that replicates the problem (or, better, a complete zip of a simple example project that replicates the issue). Until we have that, there's not much else we can do.
