### ISSUE TITLE
Free advert for the plugin

### ISSUE THREAD

**Issue by iDVB** [silvermine/serverless-plugin-cloudfront-lambda-edge#22]
Hey @jthomerson ,
Just wanted to give you the heads up that I just launched my [Lambda@Edge course](https://acloud.guru/learn/lambda-edge) last night.
It showcases your `serverless-plugin-cloudfront-lambda-edge` plugin. 

Thought you may like to know. Also, curious if you'd be open to adding a cross promotion link to it in the plugin ReadMe?

**Comment by jthomerson** [comment]
Thanks @iDVB - glad it was helpful to you! Sorry, but we're not interested in doing promotions of commercial products from our OS repos at this time.
