### ISSUE TITLE
support request body?

### ISSUE THREAD

**Issue by burmecia** [silvermine/serverless-plugin-cloudfront-lambda-edge#23]
Amazon just enabled 'include body' option in the edge lambda function association, could that be supported in this plugin? Thanks.

https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_LambdaFunctionAssociation.html

**Comment by jthomerson** [comment]
@burmecia sounds like a good idea. We don't have time right now to add it, but if you submit a PR we'll review it. Please be sure to see the README on contributing and carefully review our coding standards before submitting the PR - that will save some back-and-forth.

**Comment by suppenkelch** [comment]
Currently it is not possible to add the option 'include body' via CloudFormation.

The property is missing in documentation:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-lambdafunctionassociation.html

However, CloudFront API provides the property 'IncludeBody'
https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_LambdaFunctionAssociation.html

At this point, you have to set the option in the Management Console.

**Comment by david-gettins** [comment]
This should probably be closed as it was added in #50.
