### ISSUE TITLE
Ability to set pathPattern for html files only?

### ISSUE THREAD

**Issue by mrcoles** [silvermine/serverless-plugin-cloudfront-lambda-edge#25]
Is it possible to set a `pathPattern` to match all potential HTML requests, e.g., all the following examples:

1. `/`
2. `/index.html`
3. `/about`
4. `/about/`
5. `/about/index.html`

Alternatively, to maybe just exclude something like the following: `*.jpg, *.png, *.css, *.js`? Is this maybe possible if I set them as pathPatterns on the resource for CloudFront and then they’ll bypass the lambda? Or alternatively, should I expect those files to cache and not really matter (or do I need to set them specifically to do such?)

I’d like to use a lambda@edge function to do URL rewriting and only do so for HTML assets.

**Comment by jthomerson** [comment]
That's a CloudFront question. See https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-values-specify.html#DownloadDistValuesPathPattern

**Comment by mrcoles** [comment]
OK yeah, I was reading those docs already, I suppose I’ll punt on this idea for now—sorry for over-reaching on the issue 😯 

My best guess so far (if anyone else is running into this)—I see from [this cloudformation example](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-cloudfront.html) that I can set `CacheBehavior`s in my resource declaration for CloudFront. I’ll have to test to see if those would take priority over the lambda@edge function to essentially bypass it for the `*.jpg, *.png, *.css, *.js` files.
