### ISSUE TITLE
Could not find cache behavior  ..with path pattern 

### ISSUE THREAD

**Issue by jordanboston** [silvermine/serverless-plugin-cloudfront-lambda-edge#26]
Hi, thanks for working on this plugin!

I'm failing to understand this:
```
# This must match a path pattern in a cache behavior of the distribution:
pathPattern: 'images/*.jpg'
```

I'm getting an error `Could not find cache behavior in "MyTestDistribution" with path pattern "*.mp4"`

I have the same setup as you example except:
`ViewerProtocolPolicy: 'allow-all'`

Not sure how to resolve this.

**Comment by jordanboston** [comment]
Ok, I think I got it.  I could not find the right [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-cachebehavior.html) for the life of me.

        DistributionConfig:
          CacheBehaviors:
            - AllowedMethods:
              - "HEAD"
              - "GET"
            - CachedMethods:
              - "HEAD"
              - "GET"
            - PathPattern: '*.mp4'
            - PathPattern: '*.mov'
            - PathPattern: '*.mpd'

Maybe an update in your example won't hurt since this is required for it to work.  _Or maybe it's just me, but might not hurt._

Thanks 👍

**Comment by jordanboston** [comment]
Looks like some other items under *CacheBehaviors* are required as well:

            - TargetOriginId: 
            - ViewerProtocolPolicy: 'allow-all'
            - Compress: false
            - ForwardedValues:
                 QueryString: false
                 Cookies:
                   Forward: 'none'

**Comment by JacksonGariety** [comment]
What if I am setting `DefaultCacheBehavior`? How do I then use the `pathPattern` param?

**Comment by jthomerson** [comment]
@JacksonGariety did you find the answer to your question? I was away and missed this. Not sure I understand your question, but the README in this project shows how to assign a L@E function to the default cache behavior (leave `pathPattern` off your `lambdaAtEdge` properties)
