### ISSUE TITLE
Can you attach the same function to more than one event?

### ISSUE THREAD

**Issue by jonathanalberghini** [silvermine/serverless-plugin-cloudfront-lambda-edge#27]
Can you attach the same function to more than one event?
I am using this library?
https://github.com/jsonmaur/lambit

And it says this?
After you create your AWS Lambda function with a Node.js runtime, simply call lambit with your config object in place of the usual function code. It will handle everything related to the event for you.

const lambit = require('lambit')

exports.handler = lambit({
  cleanUrls: true,
  rewrites: [
    { source: '/*', to: '/index.html' }
  ]
})

You will need to attach this function to three out of the four triggers on your CloudFront distribution:
viewer-request origin-request viewer-response

**Comment by jthomerson** [comment]
Yes, as explained in the README under the heading "Configuring Functions to Associate With CloudFront Distributions", it is easy to associate the same function to multiple events. The third example under that heading shows how to do it. That example focuses on multiple distributions, but you should be able to do it for the same distribution with multiple event types. If you encounter an error in doing so, please open an issue with details about the error.
