### ISSUE TITLE
Support external CloudFront

### ISSUE THREAD

**Issue by brian-traceme** [silvermine/serverless-plugin-cloudfront-lambda-edge#34]
I'd like to have a serverless js conf to deploy a lambda, attaching it as a Lambda@Edge triggered lambda to a CloudFront that was defined outside of this serverless js conf.

It'd be nice to have a way to specify a CloudFront ID instead of referring to the name of a resource in this conf.

**Comment by jthomerson** [comment]
Duplicate of #15
