### ISSUE TITLE
No support for multiple path patterns

### ISSUE THREAD

**Issue by floydnoel** [silvermine/serverless-plugin-cloudfront-lambda-edge#35]
For my use case I need to associate a single edge lambda with multiple path patterns. Currently there is no way to do this as the plugin assumes only one association will be made.

**Comment by floydnoel** [comment]
figured it out, array is at the `lambdaAtEdge` level, instead of the pattern level. Only took reading the source for me to figure that out, derp.

**Comment by jthomerson** [comment]
Glad you figured it out! In case anyone else encounters this problem, I think it's covered in this heading: https://github.com/silvermine/serverless-plugin-cloudfront-lambda-edge#configuring-functions-to-associate-with-cloudfront-distributions

If that has any errors, please let us know.
