### ISSUE TITLE
serverless deploy did not fail even if the S3 bucket not exists

### ISSUE THREAD

**Issue by lardcas** [silvermine/serverless-plugin-cloudfront-lambda-edge#39]
Hi,

I noticed that the serverless deploy was completed even though S3 bucket name used in the Cloudfront Origin is not existing. Is there a way for us to handle those kind of scenario? Like if the S3 bucket used in the distribution origin is not exist, the deployment should not be proceed or completed.

Thanks,
Larry

**Comment by jthomerson** [comment]
The plugin simply makes modifications to the CloudFormation template. The issue you describe would have nothing to do with this plugin; it would be an issue with CloudFormation itself and how it's handling the creation of the resources.
