### ISSUE TITLE
Which npm package to use?

### ISSUE THREAD

**Issue by epicfaace** [silvermine/serverless-plugin-cloudfront-lambda-edge#40]
On npm, there's a package `@silvermine/serverless-plugin-cloudfront-lambda-edge` (linked to in the readme) which is version 2.1.1. There's also `serverless-plugin-cloudfront-lambda-edge` which is version 2.1.0. Is it possible to consolidate on one version and recommend one (and archive the other)?

**Comment by jthomerson** [comment]
The README already suggests the correct one (`@silvermine`), but we'd not deprecated it on NPM. I just did that.

```
jrthomer@home ~
$ npm deprecate serverless-plugin-cloudfront-lambda-edge "Moved to @silvermine org. Use @silvermine/serverless-plugin-cloudfront-lambda-edge" --otp=XXXXXX
```

![image](https://user-images.githubusercontent.com/171934/64080473-7fb80980-ccc2-11e9-8fa4-f92a671622d1.png)
