### ISSUE TITLE
Support existing Cloudfront distributions

### ISSUE THREAD

**Issue by ChristophP** [silvermine/serverless-plugin-cloudfront-lambda-edge#41]
The plugin currently expects a logical name for `distribution` in the config. It would be great to also support preexisting cloudfront distribution.

Benefits:
- integrates better for people working with other infrastructure as code tools, such as terraform.
- can help speed up deployments since cloudfront usually takes more than 20 minutes to provision.
- allows for keeping the buckets and other resources in different regions (lambda@edge needs to be in us-east-1 and serverless doesn't support multi-region deployments as far as I know)

Easy fix would be accepting a cloudfront id or arn as well.

**Comment by jthomerson** [comment]
I suggest you always search issues for a project before opening a new one. For example, a search for ["existing"](https://github.com/silvermine/serverless-plugin-cloudfront-lambda-edge/issues?utf8=%E2%9C%93&q=is%3Aissue+existing) would've netted you [some very](https://github.com/silvermine/serverless-plugin-cloudfront-lambda-edge/issues/1#issuecomment-379966146) [detailed responses](https://github.com/silvermine/serverless-plugin-cloudfront-lambda-edge/issues/14#issuecomment-384283550) that [clearly explain](https://github.com/silvermine/serverless-plugin-cloudfront-lambda-edge/issues/15#issuecomment-393511941) why your request can't be supported, and provide alternatives.

Remember, every minute open source maintainers are responding to "the same question, yet again" is a minute that we're not writing the software you know and love 😉

**Comment by ChristophP** [comment]
Got it :+1: Will do. Thanks

**Comment by jthomerson** [comment]
Interesting. Hadn't considered it from that angle. Thanks @ChristophP!
