### ISSUE TITLE
Question: support for "deploy function"?

### ISSUE THREAD

**Issue by MaxMotovilov** [silvermine/serverless-plugin-cloudfront-lambda-edge#46]
I am considering serverless for the purpose of managing [primarily] the CloudFront stack consisting of  a large number of behaviors and lambdas undergoing active development. It appears that the cloudfront-lambda-edge plugin addresses the issues inherent in deployment of the entire stack via CloudFormation, but is there a way to make the `deploy function` work with edge lambdas?

Specifically, the use case I have in mind is this:
- Within the stack, there exist multiple behaviors associated with the same event handler
- The code of the handler is changed
- The new version needs to be quickly deployed and tested, which entails updating the function itself (thus creating a new version) _and_ updating all existing triggers to use this version

It doesn't appear that serverless with or without the plugin would do more on `deploy function` than create a new version of the function. Am I wrong? Are there other tools/approaches that I am unaware of that address this use case?

Thanks in advance for all ideas and suggestions.

**Comment by jthomerson** [comment]
You're right that `deploy function` just creates a new version of the function itself. What you request, though, is not possible. To update the CloudFront trigger to point to the new version of the function requires an update to CloudFront itself. That, of course, takes the agonizing 30-45 minutes that every update to a CloudFront distribution takes. There's no way we can get around that.

Unfortunately, there's no such thing as "quickly deploy[ing] and test[ing]" Lambda@Edge functions. I recommend heavy use of unit testing. Fortunately, Lambda@Edge functions are generally very simple, and unit testing them is thus fairly easy and highly effective.
