### ISSUE TITLE
Associate different functions with multiple CacheBehaviors?

### ISSUE THREAD

**Issue by brettneese** [silvermine/serverless-plugin-cloudfront-lambda-edge#5]
We have multiple Lambda@Edge functions that operate based on different paths (specified through different CacheBehaviors.) In other words, path pattern /blah is associated with a cache behavior that runs a Lambda function, BlahLambdaFunction while path pattern /blerg.jpg is associated with a different CacheBehavior that is tied to BlergLambdaFunction. 

Is this not yet supported by the plugin? When I tried to use it it just updated by default CacheBehavoir. 😳

**Comment by alexcasalboni** [comment]
[Looking at the code](https://github.com/silvermine/serverless-plugin-cloudfront-lambda-edge/blob/master/src/index.js#L238), it seems like the plugin will always associate the Lambda Function to all the `CacheBehaviors` of the distribution. It sounds like a safe assumption, but it does not cover your use case, @brettneese.

@jthomerson I guess such a use case would require specifying an additional (optional) parameter for each Lambda Function, to match a specific cache behavior. What do you think?

**Comment by jthomerson** [comment]
I think this is a great feature for version 2.0, which is in the works. More info coming soon.
