### ISSUE TITLE
Suggestion: Validate presence of `memorySize: 128` and `timeout: 1`

### ISSUE THREAD

**Issue by skylarmb** [silvermine/serverless-plugin-cloudfront-lambda-edge#61]
It appears these must be set in order to use this plugin/lambda@edge in general otherwise you get an error on deploy (`The function memory size is larger than the maximum allowed size...`). It would be nice to catch this at the packaging stage with a simple validation

**Comment by jthomerson** [comment]
I'm not really in favor of this because we'd have to update these values any time AWS changes their limits, and then users have to upgrade to take advantage of it.
