### ISSUE TITLE
Missing JSON Schema results in "unrecognized property" warning

### ISSUE THREAD

**Issue by velovix** [silvermine/serverless-plugin-cloudfront-lambda-edge#62]
When I run a deployment using this plugin, I get the following warning:

```
Serverless: Configuration warning at 'functions.defaultDirectoryIndex': unrecognized property 'lambdaAtEdge'
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
```

According to [this page](https://www.serverless.com/framework/docs/configuration-validation/), the way to avoid this warning is to add a JSON Schema to the plugin instructing Serverless' validation logic to expect this new field.

**Comment by de1mat** [comment]
Thanks for the fix, looking forward to new version
