### ISSUE TITLE
Configuration is required

### ISSUE THREAD

**Issue by david-gettins** [silvermine/serverless-plugin-cloudfront-lambda-edge#67]
I believe this to be a bug introduced in #64.

**Problem**
Instead of saying that `lambdaAtEdge` is unrecognised (fixed) it now complains if `lambdaAtEdge` is not specified for a function.
```bash
Serverless: Configuration warning:
Serverless:   at 'functions.allow': should have required property 'lambdaAtEdge'
Serverless:   at 'functions.hello': should have required property 'lambdaAtEdge'
Serverless:   at 'functions.greet': should have required property 'lambdaAtEdge'
```

**Solution**
Make the configuration optional.

**Comment by jthomerson** [comment]
fixed in 2.2.1 thanks to @david-gettins
