### ISSUE TITLE
Lambda environment variables

### ISSUE THREAD

**Issue by redwert** [silvermine/serverless-plugin-cloudfront-lambda-edge#75]
AWS started to support the lambda@edge environment variables. I can add it manually in Lambda->Configuration->Environment variables and use this variables in my code as process.env.MY_VAR

If I add environment variables to my lambda config that doesn't affect on environment variables in my lambda@edge. The list is clear. Could you please consider adding support for env variables

**Comment by jthomerson** [comment]
@redwert two things:

1) Please cite some AWS source that says that L@E supports env vars. [Their docs](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/edge-functions-restrictions.html#lambda-at-edge-function-restrictions) still say they don't.
2) If they do, it must be supported by CloudFormation for us to make it work with this plugin. You could try commenting out [this code](https://github.com/silvermine/serverless-plugin-cloudfront-lambda-edge/blob/157f0af8cba2463c61f250dc74c34ff0c36059e9/src/index.js#L165-L179) in the plugin to see if it works.

Closing for now, but will re-open if you find that AWS really is supporting it.
