### ISSUE TITLE
Set region for edge function

### ISSUE THREAD

**Issue by mstruensee** [silvermine/serverless-plugin-cloudfront-lambda-edge#80]
In production we deploy to us-west-2 but one of the limitations to using lambdas at the edge is they must be deployed to us-east-1 ... 

how can this plugin accept a region as a param so we do not get this error during deployment ...
```
Resource handler returned message: "Invalid request provided: The function must be in region 'us-east-1'. ARN: arn:aws:lambda:us-west-2:165158022346:function:prod-radar360-edge:1 (Service: CloudFront, Status Code: 400, Request ID: 3f26f79a-e78a-4cf9-8ad3-77cc2fabf714)" (RequestToken: 8d30bd73-2edb-86fe-d89d-7c3d571cf092, HandlerErrorCode: InvalidRequest)
```

is there a way i can reference a cdn in an external/different stack?

**Comment by jthomerson** [comment]
@mstruensee what you request isn't possible. There's several similar (closed) issues in our tracker here that you can look at if you want more details on why. Put simply, this plugin simply adjusts your CloudFormation template to configure your L@E, so we can't do what you're asking. If you want to use L@E, you have to deploy to us-east-1, as the error explains.

**Comment by mstruensee** [comment]
what about  .... 
is there a way i can reference a cdn in an external/different stack?

looked at the code you grab the resources by the string name to get like 3 variables ... could it be possible to grab that from cf?
