### ISSUE TITLE
Modify serverless.yml to be Lambda only, not Lambda@Edge

### ISSUE THREAD

**Issue by michaelcuneo** [silvermine/serverless-plugin-cloudfront-lambda-edge#83]
Just wondering if there is an easy quick configuration change somewhere to modify the plugin to push to a Lambda instead of Lambda@Edge? My site doesn't need to be used outside of the region I'm in.

**Comment by jthomerson** [comment]
@michaelcuneo it's not clear what you'd hope to achieve what that? This plugin is specifically for supporting CloudFront's integration with Lambda@Edge. If you need to do something else, then you probably just need to use Serverless Framework (or other, CDK, etc) features, and don't need this plugin.
