### ISSUE TITLE
Using pre-existing CF distribution

### ISSUE THREAD

**Issue by jonasbarsten** [silvermine/serverless-plugin-cloudfront-lambda-edge#86]
Hi!

I'm deploying the CF distribution in another stack and would like to reference that when deploying lambda@edge functions.

Any suggestions on how to achieve that?

All the best

**Comment by jthomerson** [comment]
Sorry @jonasbarsten that's not supported by this plugin. This plugin exists to smooth out some odd design decisions in the Serverless framework with how it implements Lambda@Edge support (see #57) and smooth out rough edges in using L@E in general. But, it does all that by working with the resources in a single Serverless service (stack).

That said, it's less than 200 lines of code and MIT licensed, so feel free to make your own plugin based on this one that works cross-stack. You could probably do that inline in your project by defining a local plugin. But if you do make a FOSS plugin, please drop a link to it here.
